name: Publish

on:
  push:
    tags:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 8.x
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: Publishing
        run: |
          npm install
          npm test
          npm run build
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
